# Generated by Django 3.2.23 on 2024-06-11 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('varietas', models.CharField(max_length=100)),
                ('warna', models.CharField(max_length=100)),
                ('rasa', models.CharField(max_length=100)),
                ('musim', models.CharField(max_length=100)),
                ('penyakit', models.CharField(max_length=100)),
                ('teknik', models.CharField(max_length=100)),
                ('ph', models.FloatField()),
                ('boron', models.FloatField()),
                ('fosfor', models.FloatField()),
                ('prediction', models.CharField(max_length=100)),
            ],
        ),
    ]
